### ISSUE TITLE
New version roadmap

### ISSUE THREAD

**Issue by pavi2410** [Vishwas-Adiga/ai-unchive#42]
## Base (read-only)
- [x] Read and parse AIA (aia-kit)
- [x] Overview tab
- [x] Assets browser
- [x] Extensions browser
- [x] Screens browser
- [x] Blockly viewer

## Editor features
- [ ] Add, Remove assets
- [ ] Add, Remove extensions
- [ ] UI preview
- [ ] Navigation analyzer
- [ ] Properties editor
- [ ] Layout editor
- [ ] Blocks editor

## Backend features
- [ ] Connect to the buildserver
- [ ] User/Account management 
- [ ] Project management
- [ ] Import/Export AIA/AIS
